import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import classes from './background.module.css';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const poppins = Poppins({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${poppins.className} ${classes.bodyBackground} antialiased min-h-screen`}
			>
				{children}
			</body>
		</html>
	);
}
